#! /bin/bash
# Copyright (c) 1996-2012 My Company.
# All rights reserved.
#
# Author: Bob Bobson, 2012
#
# Please send feedback to bob@bob.com
#
# /etc/init.d/wvdial
#
### BEGIN INIT INFO
# Provides: wvdial
# Required-Start: 
# Should-Start: 
# Required-Stop: 
# Should-Stop:
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description: Test daemon process
# Description:    Runs up the test daemon process
### END INIT INFO

# Activate the python virtual environment
#    . /path_to_virtualenv/activate

case "$1" in
  start)
    echo "Starting server"
    # Start the daemon 
    /usr/bin/python /home/pi/Pictures/wvdial.py start
    ;;
  stop)
    echo "Stopping server"
    # Stop the daemon
    /usr/bin/python /home/pi/Pictures/wvdial.py stop
    ;;
  restart)
    echo "Restarting server"
    /usr/bin/python /home/pi/Pictures/wvdial.py restart
    ;;
  *)
    # Refuse to do other stuff
    echo "Usage: /etc/init.d/testdaemon.sh {start|stop|restart}"
    exit 1
    ;;
esac

exit 0


